// Generated by the protocol buffer compiler.  DO NOT EDIT!

package zgl.com.cn.model_hotel.hotel_bean;

import zgl.com.cn.libandroid.net.network.bean.ParcelableMessageNano;
import zgl.com.cn.libandroid.net.network.bean.ParcelableMessageNanoCreator;

@SuppressWarnings("hiding")
public final class MoHotelResponseBase extends
        ParcelableMessageNano {

  // Used by Parcelable
  @SuppressWarnings({"unused"})
  public static final android.os.Parcelable.Creator<MoHotelResponseBase> CREATOR =
      new ParcelableMessageNanoCreator<
                MoHotelResponseBase>(MoHotelResponseBase.class);

  private static volatile MoHotelResponseBase[] _emptyArray;
  public static MoHotelResponseBase[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new MoHotelResponseBase[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional .ResponseCodeEnum Code = 1;
  public int code;

  // optional string Message = 2;
  public String message;

  public MoHotelResponseBase() {
    clear();
  }

  public MoHotelResponseBase clear() {
    code = ResponseCodeEnum.Success;
    message = "";
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.code != ResponseCodeEnum.Success) {
      output.writeInt32(1, this.code);
    }
    if (!this.message.equals("")) {
      output.writeString(2, this.message);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.code != ResponseCodeEnum.Success) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeInt32Size(1, this.code);
    }
    if (!this.message.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.message);
    }
    return size;
  }

  @Override
  public MoHotelResponseBase mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 8: {
          int value = input.readInt32();
          switch (value) {
            case ResponseCodeEnum.Success:
            case ResponseCodeEnum.FullSuccess:
            case ResponseCodeEnum.DepositError:
            case ResponseCodeEnum.InvalidArgument:
            case ResponseCodeEnum.RepeatData:
            case ResponseCodeEnum.DataNull:
            case ResponseCodeEnum.DataBaseException:
            case ResponseCodeEnum.ServerException:
            case ResponseCodeEnum.NoSendMessage:
            case ResponseCodeEnum.ContentTypeNotSupport:
            case ResponseCodeEnum.ClientException:
              this.code = value;
              break;
          }
          break;
        }
        case 18: {
          this.message = input.readString();
          break;
        }
      }
    }
  }

  public static MoHotelResponseBase parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return mergeFrom(new MoHotelResponseBase(), data);
  }

  public static MoHotelResponseBase parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new MoHotelResponseBase().mergeFrom(input);
  }
}
