// Generated by the protocol buffer compiler.  DO NOT EDIT!

package zgl.com.cn.model_hotel.hotel_bean;


import zgl.com.cn.libandroid.net.network.bean.ParcelableMessageNano;
import zgl.com.cn.libandroid.net.network.bean.ParcelableMessageNanoCreator;

@SuppressWarnings("hiding")
public final class MoMobileCityResponse extends
        ParcelableMessageNano {

  // Used by Parcelable
  @SuppressWarnings({"unused"})
  public static final android.os.Parcelable.Creator<MoMobileCityResponse> CREATOR =
      new ParcelableMessageNanoCreator<
                MoMobileCityResponse>(MoMobileCityResponse.class);

  private static volatile MoMobileCityResponse[] _emptyArray;
  public static MoMobileCityResponse[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new MoMobileCityResponse[0];
        }
      }
    }
    return _emptyArray;
  }

  // repeated .MoMobileCityGroup CityData = 1;
  public MoMobileCityGroup[] cityData;

  // optional .MoHotelResponseBase BaseResponse = 2;
  public MoHotelResponseBase baseResponse;

  // repeated .MoMobileCity HotCityData = 3;
  public MoMobileCity[] hotCityData;

  public MoMobileCityResponse() {
    clear();
  }

  public MoMobileCityResponse clear() {
    cityData = MoMobileCityGroup.emptyArray();
    baseResponse = null;
    hotCityData = MoMobileCity.emptyArray();
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.cityData != null && this.cityData.length > 0) {
      for (int i = 0; i < this.cityData.length; i++) {
        MoMobileCityGroup element = this.cityData[i];
        if (element != null) {
          output.writeMessage(1, element);
        }
      }
    }
    if (this.baseResponse != null) {
      output.writeMessage(2, this.baseResponse);
    }
    if (this.hotCityData != null && this.hotCityData.length > 0) {
      for (int i = 0; i < this.hotCityData.length; i++) {
        MoMobileCity element = this.hotCityData[i];
        if (element != null) {
          output.writeMessage(3, element);
        }
      }
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.cityData != null && this.cityData.length > 0) {
      for (int i = 0; i < this.cityData.length; i++) {
        MoMobileCityGroup element = this.cityData[i];
        if (element != null) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, element);
        }
      }
    }
    if (this.baseResponse != null) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(2, this.baseResponse);
    }
    if (this.hotCityData != null && this.hotCityData.length > 0) {
      for (int i = 0; i < this.hotCityData.length; i++) {
        MoMobileCity element = this.hotCityData[i];
        if (element != null) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(3, element);
        }
      }
    }
    return size;
  }

  @Override
  public MoMobileCityResponse mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          int arrayLength = com.google.protobuf.nano.WireFormatNano
              .getRepeatedFieldArrayLength(input, 10);
          int i = this.cityData == null ? 0 : this.cityData.length;
          MoMobileCityGroup[] newArray =
              new MoMobileCityGroup[i + arrayLength];
          if (i != 0) {
            System.arraycopy(this.cityData, 0, newArray, 0, i);
          }
          for (; i < newArray.length - 1; i++) {
            newArray[i] = new MoMobileCityGroup();
            input.readMessage(newArray[i]);
            input.readTag();
          }
          // Last one without readTag.
          newArray[i] = new MoMobileCityGroup();
          input.readMessage(newArray[i]);
          this.cityData = newArray;
          break;
        }
        case 18: {
          if (this.baseResponse == null) {
            this.baseResponse = new MoHotelResponseBase();
          }
          input.readMessage(this.baseResponse);
          break;
        }
        case 26: {
          int arrayLength = com.google.protobuf.nano.WireFormatNano
              .getRepeatedFieldArrayLength(input, 26);
          int i = this.hotCityData == null ? 0 : this.hotCityData.length;
          MoMobileCity[] newArray =
              new MoMobileCity[i + arrayLength];
          if (i != 0) {
            System.arraycopy(this.hotCityData, 0, newArray, 0, i);
          }
          for (; i < newArray.length - 1; i++) {
            newArray[i] = new MoMobileCity();
            input.readMessage(newArray[i]);
            input.readTag();
          }
          // Last one without readTag.
          newArray[i] = new MoMobileCity();
          input.readMessage(newArray[i]);
          this.hotCityData = newArray;
          break;
        }
      }
    }
  }

  public static MoMobileCityResponse parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return mergeFrom(new MoMobileCityResponse(), data);
  }

  public static MoMobileCityResponse parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new MoMobileCityResponse().mergeFrom(input);
  }
}
