// Generated by the protocol buffer compiler.  DO NOT EDIT!

package zgl.com.cn.model_hotel.hotel_bean;

// enum ResponseCodeEnum
public interface ResponseCodeEnum {
  public static final int Success = 1;
  public static final int FullSuccess = 111;
  public static final int DepositError = 112;
  public static final int InvalidArgument = 220;
  public static final int RepeatData = 222;
  public static final int DataNull = 700;
  public static final int DataBaseException = 900;
  public static final int ServerException = 910;
  public static final int NoSendMessage = 980;
  public static final int ContentTypeNotSupport = 981;
  public static final int ClientException = 989;
}
